version: '3.6'

services:
  db:
    volumes:
      - target: /var/lib/postgresql/data
        type: tmpfs
  api:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/healthcheck"]
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      - BASE_URL=http://localhost:5000
      - FLASK_APP=main
      - FLASK_ENV=development
      - DEBUG=1
      - MOCK_LND=1
      - MOCK_S3=1
      - MOCK_TWITTER=1
      - DB_USERNAME=pleb
      - DB_PASSWORD=plebpass
      - SQLALCHEMY_DISABLE_POOLING=1
    ports:
      - "5000:5000"
    volumes:
      - "./api:/app"
    command: bash -c "flask db upgrade && python3 ./main.py"
  settle-bids:
    depends_on:
      api: # this is because in dev & test mode, the api is the one initializing the database, on start
        condition: service_healthy
    environment:
      - FLASK_APP=main
      - FLASK_ENV=development
      - DEBUG=1
      - MOCK_LND=1
      - MOCK_S3=1
      - MOCK_TWITTER=1
      - DB_USERNAME=pleb
      - DB_PASSWORD=plebpass
      - SQLALCHEMY_DISABLE_POOLING=1
    volumes:
      - "./api:/app"
    command: flask settle-bids
  process-notifications:
    depends_on:
      api: # this is because in dev & test mode, the api is the one initializing the database, on start
        condition: service_healthy
    environment:
      - FLASK_APP=main
      - FLASK_ENV=development
      - DEBUG=1
      - MOCK_LND=1 # probably not needed
      - MOCK_S3=1 # probably not needed
      - MOCK_TWITTER=1
      - DB_USERNAME=pleb
      - DB_PASSWORD=plebpass
      - SQLALCHEMY_DISABLE_POOLING=1
    volumes:
      - "./api:/app"
    command: flask process-notifications
