version: '3.6'

services:
  db:
    build:
      context: ./
      dockerfile: ./services/postgres/Dockerfile
    networks:
      - db_network
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    image: plebeianmarket-api
    depends_on: [db]
    restart: on-failure
    stop_grace_period: 1m
    networks:
      - db_network
      - proxy
  settle-bids:
    image: plebeianmarket-api
    depends_on: [db]
    restart: on-failure
    stop_grace_period: 1m
    networks:
      - db_network
  process-notifications:
    image: plebeianmarket-api
    depends_on: [db]
    restart: on-failure
    stop_grace_period: 1m
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
  proxy:
    driver: bridge
